# Generated by Django 3.2.7 on 2021-09-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='casual',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='others',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='sick',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
