# Generated by Django 3.2.7 on 2021-09-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_auto_20210913_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='casual',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='others',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='sick',
            field=models.IntegerField(null=True),
        ),
    ]
