# Generated by Django 3.2.7 on 2021-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_auto_20210913_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='casual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='others',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='sick',
            field=models.IntegerField(default=0),
        ),
    ]
