# Generated by Django 3.2.7 on 2021-09-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('details', models.CharField(max_length=100, null=True, unique=True)),
                ('start_date', models.CharField(max_length=100, null=True, unique=True)),
                ('end_date', models.CharField(max_length=100, null=True, unique=True)),
                ('holiday_type', models.CharField(max_length=100, null=True, unique=True)),
                ('year', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
