# Generated by Django 3.2.7 on 2021-09-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('floor', models.CharField(max_length=7, null=True)),
                ('room', models.CharField(max_length=7, null=True)),
                ('is_active', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
